# yaml (Yaml Ain't Markup Language')
server:
  port: 9025

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS

spring:
  datasource:
    #url: jdbc:mariadb://Ibbinstance.cjraovccfifn.us-west-1.rds.amazonaws.com:3306/ibbdb
    #username: ibbuser
    #password: password
    #driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:h2:mem:mydb
    url: jdbc:h2:file:~/spring-boot-h2-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  security:
    jwt:
      secret: 5v8y/B?E(H+KbPeShVmYq3t6w9z$C&F)
    user:
      name: user
      password: password
    oauth2:
      client:
        registration:
          google:
            clientId: 583369200281-ubok9tafv7bf6rm259jhklq30clh2fbs.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  jpa:
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
